asciidwango/js-primer

- .travis.yml
- package.json
Travis CIで
- npm test
- npm run test:example
を走らせます。
refs: #11
> test(travis): add Travis CI integration

- README.html.md
- README.md
- package.json
> chore(meta): リポジトリ名をjs-primerにリネーム

- meeting/2016-06-28/README.md
> feat(meta): add 2016-06-28 meeting notes

- README.html.md
- README.md
- book.json
タイトル "JavaScriptの入門書"って入れてるけど #js-primer とかにした方がいいかな?
close #58
> chore(readme): メタ情報を更新、Twitterボタンを追加

- LICENSE
- README.md
READMEとLICENSEファイルで明記した
- 文章はCC BY-NC
- コードはMITライセンス
#55 で決定した内容を反映
refs #55
close  #37
> feat(license): add LICENSE file

- source/ajaxapp/entrypoint/README.md
https://github.com/asciidwango/js-primer/pull/88#discussion_r71061227 で出た話
> chore(ajaxapp): ログ出力に関する記述を修正

- meetings/2016-07-29/README.md
https://github.com/asciidwango/js-primer/issues/96 のミーティングノートです。
何かあればここにコメントしてください。
close #96
> 2016-07-29のミーティングノート

- source/basic/operator/README.md
> feat(operator): fix typo

- meetings/2016-09-09/README.md
2016年9月9日のミーティングノートです。 #139 
質問や意見などはこのIssueへ
close #139
> docs(meetings): 2016-09-09 Meeting Notes

- source/basic/data-type/README.md
- source/basic/implicit-coercion/README.md
"IEEE 754 方式" => "IEEE 754"と書くだけにした。
> fix(data-type): "IEEE 754"という表記に変更

- source/ajaxapp/promise/src/index.js
- source/ajaxapp/src/index.js
> refactor(ajaxapp): userIdをエンコードする

- meetings/2016-10-28/README.md
2016年10月28日に開催したミーティングの記録です。 #154
意見や質問などはこのPull Requestに書いてください
> chore(meetings): 2016-10-28のミーティングノート

- source/README.md
> fix(nodecli): 目次の変更が漏れてたので修正

- source/intro/goal/README.md
#103 の目的に追加した。
これは、パーフェクトJavaScriptのようなJava言語との比較が度々でてくる というのは避けたいので、目的として追加します。
必要ならば他の言語と比較することは正しいですが、比較すること自体は目的ではありません。
> feat(goal): 他の言語と比較することが目的ではない 事を追加

- meetings/2016-11-30/README.md
2016年11月30日のミーティングノートです
意見や質問はこのPRに書いてください。
close #169
> feat(meetings): 2016-11-30のミーティングノート

- meetings/2017-01-20/README.md
2017-01-20のミーティングノートです。
意見や質問などはここに書いてください。
close #178
> 2017-01-20 ミーティングノート

- meetings/2017-02-24/README.md
2017年2月24日のミーティングノートです。
意見や疑問はここにコメントしてください。
close #191
> feat(meta): 2017-02-24 Meeting Notes

- source/basic/implicit-coercion/README.md
間違ってるわけではないが文脈的にparseFloatの方が自然なのかな, と.
もし意図があるのであれば申し訳ないですが閉じて頂けると.
> chore: parseInt -> parseFloat

- meetings/2017-05-26/README.md
2017年5月26日に実施したミーティングの記録です。
意見や質問などはこのPull Requestに書いてください。
close #233
> feat(meetings): 2017-05-26のミーティングログ

- book.json
- package.json
GitBook上の表示を見ながら気づく問題も多いと思うので、GitBookから直接Issueを立てれるプラグインを作った。
https://github.com/azu/gitbook-plugin-github-issue-feedback
> feat(GitBook): add github-issue-feedback

- source/basic/data-type/README.md
> fix(data-type): typeof nullのリンクが壊れているのを修正

- source/landing/index.html
www.ecma-international.org/ecma-262/ ES2017が出たので
> chore(web): ECMAScript 2017

- source/use-case/ajaxapp/display/README.md
- source/use-case/ajaxapp/display/src/index.js
- source/use-case/ajaxapp/promise/src/index.js
- source/use-case/ajaxapp/src/index.js
> Ajaxapp fix

- meetings/2017-07-21/README.md
2017年7月21日のミーティングノートです。
疑問や意見はこのPull Requestに書いてください。
close #263
> feat(meeting): 2017-07-21のミーティングノート

- source/basic/array/README.md
#49 `{{book.console}}` が抜けているのでまとめて追加。
それぞれのパラグラフを2-3センテンスで区切るように調整
> refactor(array): code実行ブロックの追加

- meetings/2017-08-24/README.md
2017-08-24に開催したミーティングの記録です。 #275 
意見や質問などはこのPull Requestに書いてください
close #275
> feat(meeing): 2017-08-24のミーティング

- .travis.yml
- package.json
> perf(travis): enable build stage

- source/basic/object/README.md
> fix(object): fix typo

- meetings/2017-09-28/README.md
2017年9月28日に開催したミーティングの記録です。
意見や質問などはこのPull Requestに書いてください
close #299
> feat(meeting): 2017-09-28のミーティングノート

- source/README.md
> fix(book): indexのタイトルを変更

- source/README.md
- source/basic/math/README.md
#100
randomとmin,maxしか触れてない すごくあっさりした内容になった。
やっぱりこれは章ではなく節レベルかなー あとでマージされそう
> feat(basic): Math

- .textlintrc
- package.json
- yarn.lock
https://github.com/textlint-ja/textlint-rule-preset-ja-technical-writing/releases/tag/2.0.0
> chore(rule): textlint-rule-preset-ja-technical-writing 2.0へ更新

- source/README.md
> feat(module): モジュールをSUMMMARYに追加

- source/use-case/nodecli/argument-parse/README.md
Fix #313 
長く触れすぎ？どこまで書くべきかよくわからなかった
> fix(nodecli): package-lock.jsonについての記述を追加

- .textlintrc
- source/basic/introduction/README.md
ref:
- https://github.com/asciidwango/js-primer/issues/359
@azu 例えばこういうことでしょうか？(唐突な押し込みPull Request)
> fix: add permanent notation

- book.json
- package.json
- source/_layouts/website/page.html
> chore(docsearch): update search

- source/basic/function-this/README.md
以下のように、コードがうまく動いていない部分が見られたので、
`use strict`及び`console.log`を追加しました。ご確認よろしくお願い致します。
> Console内のコードの修正 (function-this)

- source/basic/class/README.md
> feat(class): 静的メソッドの継承

- source/use-case/todoapp/index.html
- source/use-case/todoapp/src/EventEmitter.js
- source/use-case/todoapp/src/index.js
- source/use-case/todoapp/src/models/TodoItem.js
- source/use-case/todoapp/src/models/TodoList.js
- source/use-case/todoapp/src/views/TodoListView.js
- source/use-case/todoapp/style.css
フィルターは思ったより面倒なことになったのでおまけコースで検討する
> refactor(todo): TodoにCSSをあてた

- book.json
- package.json
- source/_layouts/website/header.html
- source/_layouts/website/page.html
- source/basic/implicit-coercion/README.md
- source/use-case/todoapp/src/views/TodoListView.js
> fix(website): fix search/header design

- package.json
- source/_layouts/website/page.html
- source/sw-register.js
- source/sw.js
- workbox-config.js
Related #431 
Workboxを使ってservice workerを導入してみました。
Localで, Offlineアクセスできていることが確認できています。
今回は, generateSWではなく, google analyticsの設定を加えるため, 
injectManifestを使用しました。
Cacheの作り方は, ひとまず`_book`以下の(md以外)全てのファイルをCacheしています。
そもそも確認方法がよくわからなかったので見て頂けたらと思います
Cacheするファイルや有効期限を設けた方がいいなどあれば、適宜修正をかけたいと考えています
> feat(website): Service Workerの導入

- book.json
- package.json
- source/use-case/todoapp/event-model/README.md
#4 
#454 でTodoのまとめにはチェックボックスで振り返りを入れるという話をした
> refactor(tooapp): まとめのチェックボックスを追加

- source/sw.js
Fix #466 
とりあえず、`html,css,js`ファイルにアクセスした場合には、NetworkFirstになるようにしました
> fix(website): Add cache strategy

- source/basic/function-scope/README.md
Fix #467
Issueにあがっていたように、文言を修正しました
> fix(function-scope): 文言の変更

- source/use-case/ajaxapp/promise/README.md
> feat(usecase/ajaxapp): Fetch APIのコラム

- .travis.yml
- package.json
- source/use-case/todoapp/package.json
> perf(ci): split e2e from testg

- meetings/2018-06-29/README.md
2018年6月29日のミーティングノートです。
質問は意見はこのPRへ
Fix #492
> feat(meeting): 2018-06-29 Meeting Notes

- source/landing/index.html
ES2018が正式にリリースされたので
http://www.ecma-international.org/news/index.html
> fix(landing): Update to ES2018

- netlify.toml
- source/basic/variables/README.md
> fix(variables): fix undefined

- meetings/2018-07-26/README.md
2018年7月26日のミーティングノートです。
意見や質問はこのPRへお願いします。
fix #525
> feat(meetings): 2018年7月26日のミーティングノート

- meetings/2018-09-06/README.md
2018年9月6日に行われたミーティングの記録です。
ご意見やご質問はこのPRに書いてください
close #531
> feat(meeting): 2018年9月6日のミーティングノート

- CONTRIBUTING.md
「書かれおり」は明らかに脱字。修正ついでに読みやすいよう改変
> fix grammar

- source/use-case/setup-local-env/README.md
https://github.com/npm/npm -> https://github.com/npm/cli に移動しています。
> npmのリポジトリが移動している

- source/basic/async/README.md
> fix(async): fix math.random()

- source/basic/loop/src/break/break-find-example.js
- source/basic/loop/src/break/find-even-break-example.js
- source/basic/loop/src/break/find-even-return-example.js
変数名、関数名の綴りを見直し
isEventIncluded→isEvenIncluded
> fix(loop): fix typo

- meetings/2018-12-17/README.md
2018-12-17のミーティングノートです。
意見や質問はこのPull Requestへ。
close https://github.com/asciidwango/js-primer/issues/592
> 2018年12月17日のミーティングノート

- source/_layouts/website/page.html
Refs: https://github.com/azu/service-worker-updatefound-refresh-dialog
> feat(website): add refresh dialog for service worker

- source/basic/data-type/README.md
Refs https://github.com/asciidwango/js-primer/issues/610
解説: https://github.com/asciidwango/js-primer/issues/610#issuecomment-449641459
このコラム自体が少し無駄な感じ(不安を煽る感じ)はするので、将来変更の余地がありそう。
> fix(data-type): var undefinedのコード例を修正

- source/basic/math/README.md
https://github.com/asciidwango/js-primer/issues/599
> feat(math): Mathに整数丸めを追加

- source/basic/function-declaration/README.md
> fix missing semicolon

- tools/strip-markdown-extension.js
> feat(tools): strip-markdown-extension.jsですべての変数置換に対応

- meetings/2019-02-25/README.md
2019年2月25日のミーティングノートです。
意見や質問などがあればこのPull Requestへ。
close #669
> feat(meeting): 2019-02-25 Meeting Note

- source/basic/string/README.md
とても簡潔かつ丁寧にまとめてあって、助かっています。
ありがとうございます。
「文字列」のページのサンプルコードで、`"Script"`の文字列が重複していたので変数を使うようにしました。
ご確認をお願いします。
> fix(string):文字列の重複を修正

- source/basic/class/README.md
fixes #704 
- typo 3件
- 相対パスの間違い1件
修正しました。
> クラスページのリンク切れを修正

- package.json
- source/use-case/README.md
- source/use-case/nodecli/README.md
- source/use-case/setup-local-env/README.md
- tools/generate-summary.js
- tools/update-summary.sh
> feat(use-case): ユースケースの目次を追加

- .prettierignore
- source/use-case/nodecli/refactor-and-unittest/README.md
- source/use-case/nodecli/refactor-and-unittest/src/package.json
- source/use-case/nodecli/refactor-and-unittest/src/test/fixtures/expected.html
> fix(usecase/nodecli): mochaのバージョン固定とfixtureの修正

- meetings/2019-03-25/README.md
2019年3月25日のミーティングノートです。
意見や質問はこのPull Requestに書いてください。
fix #734
> feat(meeting): 2019-03-25のミーティングノート

- source/use-case/nodecli/md-to-html/README.md
- source/use-case/nodecli/md-to-html/src/package.json
- source/use-case/nodecli/refactor-and-unittest/src/package.json
> fix(usecase/nodecli): npmパッケージバージョンを固定

- source/use-case/ajaxapp/display/README.md
- source/use-case/ajaxapp/display/src/index.js
- source/use-case/ajaxapp/promise/README.md
- source/use-case/ajaxapp/xhr/README.md
- source/use-case/ajaxapp/xhr/src/index.js
エラー内容を表示する箇所を、 `console.log` -> `console.error` に修正しました。
ご確認いただければ :pray:
> chore: fit console method to the context

- meetings/2019-04-22/README.md
2019年4月22日のミーティングノートです。
意見や質問はこのPull Requestにお願いします。
close #759
> feat(meeting): 2019年4月22日のミーティングノート

- source/basic/ecmascript/README.md
スペルミスを修正しました
Stadard -> Standard
> ECMAScriptページのtypo修正

- source/use-case/todoapp/update-delete/README.md
todoapp/update-deleteでの完成形のリンクが間違っていたため修正しました。
> fix link: todoapp/update-delete

- source/basic/async/README.md
#770 の修正です。
Promiseチェーンの最後で処理を書く -> Promiseチェーンの最後に処理を書く
> Fix typo for #770

- source/basic/array/README.md
> chore 脱字修正

- source/basic/class/README.md
> Fix コード例のミスを修正

- source/basic/read-eval-print/README.md
脱字の修正を行いました。
お手すきの際にご確認いただけますと幸いです。
> chore: 脱字修正

- source/basic/operator/README.md
> chore: 誤字修正

- source/use-case/ajaxapp/src/index.js
https://github.com/asciidwango/js-primer/issues/812
完成形のソースコードを書き直しました
> refactor(usecase/ajaxapp): ajaxappのサンプルアプリをfetch+async/awaitに書き換え

- source/basic/error-try-catch/README.md
> refactor try...catchのコードを修正

- source/basic/variables/README.md
- source/basic/variables/src/const-do-not-assign-invalid.js
- source/basic/variables/src/let-duplicated-define-invalid.js
コード例の前にエラーメッセージを出すのはどうだろ?
refs #814
> refactor(variable): エラーメッセージを表示するように変更

- source/basic/operator/README.md
> chore: fix typo (undefeined -> undefined)

- source/basic/comments/README.md
> feat(comment): add conslusion

- source/README.md
- source/use-case/ajaxapp/README.md
- source/use-case/ajaxapp/display/README.md
- source/use-case/ajaxapp/display/src/index.js
https://github.com/asciidwango/js-primer/issues/812
displayのセクションは JSONパースの必要がなくなった部分の書き換えと、index.jsの書き直し。
次のセクションでthenチェーン => async/awaitへのリファクタリングの流れなので、今はthenの中で処理してる
> fix(usecase/ajaxapp): displayのセクションをFetch APIベースに書き直し

- book.json
- source/landing/index.html
> fix(ECMAScript): ECMAScript 2019に変更

- meetings/2019-07-01/README.md
2019年7月1日のミーティングノートです
質問や意見はこのPull Requestに書いて下さい。
close #860
> feat(meetings): 2019-07-01のミーティングノート

- .travis.yml
> refactor(travis): move E2E test to stage:test

- source/use-case/ajaxapp/display/README.md
- source/use-case/ajaxapp/entrypoint/README.md
- source/use-case/ajaxapp/http/README.md
- source/use-case/ajaxapp/promise/README.md
> feat(usecase/ajaxapp): ajaxappのユースケースにチェックリストを追加

- source/use-case/nodecli/argument-parse/README.md
- source/use-case/nodecli/helloworld/README.md
- source/use-case/nodecli/md-to-html/README.md
- source/use-case/nodecli/read-file/README.md
- source/use-case/nodecli/refactor-and-unittest/README.md
https://github.com/asciidwango/js-primer/issues/813
粒度がばらついていて微妙な気がする...
> feat(usecase/nodecli): nodecliユースケースにチェックリストを追加

- source/basic/async/README.md
> refactor(basic/async): 冗長な箇所のリファクタリング

- source/basic/ecmascript/README.md
fix https://github.com/asciidwango/js-primer/issues/861
> fix(ecmascript): 2017 年以降は省略

- source/basic/map-and-set/README.md
> feat(map-and-set): まとめを追加

- source/basic/async/demo/try-catch-error-in-sync-callback.js
- source/basic/async/demo/try-catch-sync-callback.js
- source/basic/async/example/try-catch.js
- source/basic/error-try-catch/README.md
- source/basic/json/README.md
- source/basic/json/src/circular-reference.js
- コラムじゃなくて本文に変更
- 量が少ないしコラムじゃなくてよさそう
refs #713
> feat(json): まとめを追加

- source/basic/date/README.md
> feat(date): まとめを追加

- source/basic/math/README.md
> feat(math): まとめを追加

- source/use-case/ajaxapp/promise/README.md
- source/use-case/ajaxapp/promise/src/index.js
Eventオブジェクトは特に使ってなさそうで、Responseオブジェクトのプロパティを参照するのが正しいかなと思って修正してみました。
> chore: Responseオブジェクトを使ったエラーメッセージにする

- source/basic/string/README.md
細かな点ですが、誤字を修正いたしました。
修正：
正規表現によ**り**インデックスの取得 → 正規表現によ**る**インデックスの取得
> fix(string): fix typo

- source/basic/introduction/README.md
モジュールのリンク先が変わっていたのようなので修正しました。
> chore: fix link

- meetings/2019-08-05/README.md
2019年8月5日のミーティングログです。
質問や意見はこのPull Requestにお願いします。
close #924
> feat(meeting): 2019-08-05のミーティングログ

- source/basic/map-and-set/README.md
細かい点ですが、誤字と思われるところを修正しました。
値を弱い参照をもつ -> 値を弱い参照でもつ
> chore: fix typo

- source/basic/ecmascript/README.md
> chore(ecmascript): fix typo

- source/basic/implicit-coercion/README.md
型が異なる変数の計算の以下2例が、 あまり違いを表現できていないに見えたので、
```javascript
console.log(x + y + z); // => "123"
console.log(y + x + z); // => "213"
```
数値同士の計算が発生する以下の例を追加しました
```javascript
console.log(x + z + y); // => "42"
```
大変ありがたく読ませて頂いております!
> chore(implicit-coercion): change code example for better understanding

- source/use-case/todoapp/final/final/src/App.js
変数名が変わっていたので、他と揃えました。
Closes #946
> chore: 変数名を揃える

- source/basic/data-type/README.md
> fix(date-type): undefinedのコラムを修正

- meetings/2019-09-09/README.md
2019年9月9日のミーティングノートです。
質問や意見はこのPull Requestに書いてください。
close #956
> feat(meeting): 2019-09-09 ミーティングノート

- source/intro/authors/README.md
#971 
@azu とりあえず箱だけ作っておくのであとで更新してください
> feat(intro/authors): 著者紹介のファイル追加

- source/use-case/todoapp/form-event/README.md
> fix: 助詞を修正

- source/README.md
- source/intro/authors/README.md
fix #985 
@lacolaco 他の書籍見ててTwitterとGitHub載せてるのもあったので、なんとなく足してみたけど入れる?
> feat(authros): add azu

- source/intro/authors/README.md
> fix(intro/authors): laco 著者紹介修正

- source/use-case/ajaxapp/display/src/index.js
- source/use-case/ajaxapp/http/README.md
- source/use-case/ajaxapp/http/src/index.js
- source/use-case/ajaxapp/promise/README.md
- source/use-case/ajaxapp/promise/src/index.js
> fix(usecase/ajaxapp): ネットワークエラーのハンドリングを修正

- meetings/2019-12-10/README.md
2019年12月10日のミーティングログです。
意見や質問はこのPull Requestに書いてください。
fix #1008
> feat(meeting): 2019-12-10のミーティングログ

- source/basic/prototype-object/README.md
> [プロトタイプオブジェクト]用字用語の統一・編集済

- meetings/2020-01-16/README.md
2020年1月16日のミーティングノートです。
意見や質問はこのPull Requestに書いてください。
fix #1026
> feat(meetings): 2020-01-16 Meetings Notes

- tools/applescript/modules/firefox.ts
> fix(screenshot): add -o

- meetings/2020-02-14/README.md
2020年2月14日のミーティングログです。
意見や質問はこのPRにお願いします。
fix #1073
> feat(meetings): 2020-02-14 ミーティングログ

- .textlintrc.js
- package.json
- source/basic/data-type/README.md
- textlint/textlint-rule-no-use-column/index.js
- textlint/textlint-rule-no-use-column/package.json
> fix(data-type): "コラム" という言葉を使うのを避ける

- source/basic/json/README.md
> fix(basic/json): replacer引数についての記述を修正

- TeX/chap24.tex
> JSONの章を修正 (md: #1103)

- source/use-case/nodecli/refactor-and-unittest/src/main.js
- source/use-case/nodecli/refactor-and-unittest/src/test/md2html-test.js
> fix(usecase/nodecli): encodingの指定方法を統一

- TeX/chap31.tex
> nodecliの章 encodingとreadfilesyncについてのコメントを修正

- meetings/2020-04-01/README.md
2020-04-01のミーティングノートです。
意見や質問はこのPull Requestにお願いします。
fix #1116
> feat(meeting): 2020-04-01のミーティングノート

- .github/workflows/test.yml
- package.json
- source/use-case/nodecli/argument-parse/README.md
- source/use-case/nodecli/argument-parse/src/package-lock.json
- source/use-case/nodecli/argument-parse/src/package.json
- source/use-case/nodecli/md-to-html/README.md
- source/use-case/nodecli/md-to-html/src/package-lock.json
- source/use-case/nodecli/md-to-html/src/package.json
- source/use-case/nodecli/read-file/src/package-lock.json
- source/use-case/nodecli/read-file/src/package.json
- source/use-case/nodecli/refactor-and-unittest/README.md
- source/use-case/nodecli/refactor-and-unittest/src/package-lock.json
- source/use-case/nodecli/refactor-and-unittest/src/package.json
とりあえずPRを作成
- mocha@7
- commander@5
- marked@0.8
fix #1106 
fix #1111 
fix #1112
> fix(use-case/nodecli): パッケージのバージョン更新

- source/_layouts/website/header.html
- source/_layouts/website/page.html
> fix(website): fix footer on mobile

- TeX/chap27.tex
> fix(chap27): シンタックスエラー -> 構文エラー

- TeX/chap31.tex
> fix(chap31): commanderのバージョンを5.0に修正

- .github/FUNDING.yml
> chore(github): add .github/FUNDING.yml

- source/use-case/setup-local-env/README.md
@js-primer/local-serverについてgithubの該当リポジトリへのリンクがされていなかったためにリンクを付けてみました。
(118,193行目を修正しました。)
当方初めてでやり方間違っていたらすみません。
> Update README.md line 118,193

- README.md
> Fix book url

- source/basic/class/README.md
> fix(class): console.logの抜けを修正

- source/use-case/todoapp/final/create-view/src/view/TodoItemView.js
- source/use-case/todoapp/final/final/src/view/TodoItemView.js
- source/use-case/todoapp/final/more/src/view/TodoItemView.js
- source/use-case/todoapp/update-delete/README.md
- source/use-case/todoapp/update-delete/add-checkbox/src/App.js
- source/use-case/todoapp/update-delete/delete-feature/src/App.js
- source/use-case/todoapp/update-delete/update-feature/src/App.js
> refactor: inputの閉じタグ削除

- source/basic/async/README.md
> chone: fix typo

- package-lock.json
- package.json
> chore(deps): update to honkit@3.4.0

- source/use-case/todoapp/final/README.md
> chore: -> を → に変更

- source/basic/operator/README.md
> fix(operator): リンク切れを修正

- package-lock.json
- package.json
https://github.com/honkit/honkit/releases/tag/v3.5.1
> chore(deps): update honkit@3.5.1

- source/basic/module/src/re-export-invalid.js
> feat(module): ` export * as ns from "mod";` の追加

- source/use-case/nodecli/refactor-and-unittest/README.md
「ユニットテストを記述する」におけるユニットテスト成功時の説明とメッセージを修正しています。
> ユニットテスト成功時の説明とメッセージを修正(#1235)

- .github/workflows/test.yml
- package-lock.json
- package.json
- source/basic/object/README.md
- source/basic/operator/README.md
- test/markdown-doc-test.js
Nullish coalescing演算子(??) のテストが落ちてない #1205
> CI: add Node.js 14

- source/basic/prototype-object/README.md
「インスタンス化したときに」を削除するものです。
#1239
> Issues #1239 のPRです

- source/basic/object/README.md
> fix object README.md

- source/basic/json/README.md
> chore(basic/json): リンクを https に変更する

- CONTRIBUTING.md
> fix(CONTRIBUTING): 表記の改善

- source/basic/class/README.md
> chore: unify the expression of [Note]

- source/use-case/ajaxapp/display/src/index.html
- source/use-case/ajaxapp/entrypoint/src/index.html
- source/use-case/ajaxapp/http/src/index.html
- source/use-case/ajaxapp/promise/src/index.html
- source/use-case/ajaxapp/src/index.html
- source/use-case/setup-local-env/src/index.html
- source/use-case/todoapp/app-structure/todo-html/index.html
- source/use-case/todoapp/entrypoint/first-entry/index.html
- source/use-case/todoapp/entrypoint/module-entry/index.html
- source/use-case/todoapp/event-model/event-emitter/index.html
- source/use-case/todoapp/final/create-view/index.html
- source/use-case/todoapp/final/final/index.css
- source/use-case/todoapp/final/final/index.html
- source/use-case/todoapp/final/more/index.html
- source/use-case/todoapp/form-event/add-todo-item/index.html
- source/use-case/todoapp/form-event/prevent-event/index.html
- source/use-case/todoapp/update-delete/add-checkbox/index.html
- source/use-case/todoapp/update-delete/delete-feature/index.html
- source/use-case/todoapp/update-delete/input-checkbox/index.html
- source/use-case/todoapp/update-delete/update-feature/index.html
- tools/applescript/src/launch-firefox.ts
- tools/applescript/src/screenshot-dev-tools.ts
- tools/applescript/src/screenshot-only.ts
- tools/applescript/src/screenshot.ts
`<!DOCTYPE html>` を追加
refs #1263
> fix(todo): <!DOCTYPE html>を追加

- source/basic/object/README.md
> fix(object): shallow copyのコメントを修正

- book.json
> feat: ES2021にアップデート

- CONTRIBUTING.md
- source/use-case/todoapp/app-structure/README.md
- source/use-case/todoapp/entrypoint/README.md
- source/use-case/todoapp/event-model/README.md
- source/use-case/todoapp/final/README.md
- source/use-case/todoapp/form-event/README.md
- source/use-case/todoapp/update-delete/README.md
こちらの方がコード的に綺麗に見える。
index.jsに余計なものが入らない。
fix #1424
> fix(todoapp): externalResourcesを使ってfinal/index.cssを読み込むように修正

- source/basic/function-declaration/README.md
Closes: #1427 
azuさんの仰られた例に書き変えました。
> Fix example in 関数式 and Arrow Function

- meetings/2022-08-18/README.md
2022-08-18のミーティングログです。
意見やコメントはこのPRかDiscussionに書いてください
close https://github.com/asciidwango/js-primer/discussions/1460
> feat(meeting): 2022-08-18のミーティングログ

- source/cheatsheet/README.md
>  fix(cheat-sheet): remove ;

- source/basic/map-and-set/README.md
Closes #1468
`fetch` の使い方やコーディングスタイルに問題がありましたらお手数ですがご指摘ください。
> chore: use fetch instead of XHR

- meetings/2022-10-06/README.md
2022-10-06のミーティングノートです。
質問や意見は、このPRか次のdiscussionsへ
<div type='discussions-op-text'>
<sup>Originally posted by **azu** October  6, 2022</sup>
[2022-10-06のミーティングスレ](https://github.com/asciidwango/js-primer/discussions/1480)</div>
> feat(meeting): 2022-10-06のミーティングノート

- README.md
- book.json
- meetings/2017-02-24/README.md
- source/use-case/nodecli/argument-parse/README.md
- source/use-case/nodecli/helloworld/README.md
> feat: Node.js 16 LTSとnpm 8へアップデート

- source/basic/ecmascript/README.md
> refactor(ecmascript): ECMAScriptの章のリファクタリング

- source/use-case/todoapp/app-structure/README.md
- source/use-case/todoapp/entrypoint/README.md
- source/use-case/todoapp/event-model/README.md
- source/use-case/todoapp/final/README.md
- source/use-case/todoapp/form-event/README.md
- source/use-case/todoapp/update-delete/README.md
Todoの章 後半がコード変更しながら読むの難しい感じもした。
やっぱりコードが長くなると説明が難しい
> refactor(todoapp): Todoアプリの章のリファクタリング

- source/basic/implicit-coercion/README.md
> fix: jsdocのURLを修正

- .textlintrc.js
- source/cheatsheet/README.md
- source/intro/preparation/README.md
> fix(cheatsheet): fix link

- CONTRIBUTING.md
> feat(CONTRIBUTING): リリースフローを追加

- CONTRIBUTING.md
- source/use-case/ajaxapp/http/README.md
> refactor(ajaxapp): Fetchの言い回しを修正

- package-lock.json
- package.json
textlint 13!
- https://github.com/textlint/textlint/releases/tag/v13.0.0
- https://textlint.github.io/blog/2023/01/27/textlint-13.html
> chore(deps): update to textlint 13.0.0

- source/basic/operator/README.md
console.log の出力結果に関するコメントの書き方が他と整合するよう（そして Doctest が実行されるよう）修正しました。
> fix: console.log の出力結果に関するコメントの書き方を修正

- source/basic/loop/README.md
#1172
出力のないサンプルコードかつ数行先に出力のある同等コードが存在するため実行ボタンを削除しました｡
> 何も出力されないコードのため､実行ボタンを削除

- source/basic/module/src/named-import.js
https://github.com/asciidwango/js-primer/pull/1615 の修正漏れ
> fix(module): remove quote from function bar

- source/intro/README.md
"謝辞"に第2版でのレビューアーを追加
- 全角の括弧と半角スペースだけ統一しています。
追加順はランダムにソートしました。
```js
copy(`- staticWagomU（林 永遠）
- 2nofa11（ツノ）
- keisuke kudo（工藤佳祐）
- haruguchi（池奥 悠馬）
- kakts（阿久津 恵太）
- 藤野慎也（morinokami）
- r-shirasu
- kobakazu0429（小畠 一泰）
- 滝谷修`.split("\n").sort(function(){return Math.random() - 0.5}).join("\n"))
```
Preview URL: https://deploy-preview-1627--js-primer.netlify.app/intro/#thanks
---
@kakts @KeisukeKudo @staticWagomU @nikukyugamer @2nofa11 @r-shirasu @haruguchi-yuma @kobakazu0429 @morinokami 
名前の表記ミスや抜け漏れがないか確認をお願いします。
3/1にマージする予定です(修正自体はもう少し猶予があります)。
> feat: 第2版のレビューアーへの謝辞を追加

- meetings/2023-03-13/README.md
2023-03-13のミーティングノートです。
意見や質問はこのPRかDiscussionへ
- [2023-03-13のミーティングアジェンダ · asciidwango/js-primer · Discussion #1648](https://github.com/asciidwango/js-primer/discussions/1648)
> feat(meeting): 2023-03-13のミーティングノート

- source/use-case/todoapp/final/create-view/src/view/TodoItemView.js
- source/use-case/todoapp/final/create-view/src/view/TodoListView.js
- source/use-case/todoapp/final/final/src/view/TodoItemView.js
- source/use-case/todoapp/final/final/src/view/TodoListView.js
- source/use-case/todoapp/final/more/src/view/TodoItemView.js
- source/use-case/todoapp/final/more/src/view/TodoListView.js
idはnumberなので、JSDocをstring -> numberへ変更
> fix(todo): id: numberへの修正

- package-lock.json
- package.json
https://github.com/honkit/honkit/releases/tag/v5.0.0
> chore(deps): update to HonKit 5

- book.json
> feat: ES2023 book.jsonの更新

- source/basic/function-scope/README.md
> fix(function-scope): fix typo

- source/_layouts/website/page.html
> fix(website): tableの横スクロールをサポート

- package-lock.json
- package.json
> feat: REPLをError Causeに対応

- source/basic/loop/README.md
> fix(loop): number → num

- README.md
- source/intro/README.md
- source/landing/index.html
- [JavaScript Primer 改訂2版【委託】 - 達人出版会](https://tatsu-zine.com/books/javascript-primer-2ed)
へのリンクへ変更
> fix(website): 改訂2班の電子版へのリンクを追加

- CONTRIBUTING_EXPENSE.md
- tools/calc-contribute-expense.mjs
タスクに対する金額の計算方法とOpen Collectiveでの請求方法のドキュメントを追加
fix #1736
> feat(CONTRIBUTING_EXPENSE): Open Collectiveの手引きを追加

- package-lock.json
- package.json
- tools/typo-finder.cjs
> chore: remove lodash

- source/basic/class/README.md
parentFeild → parentField
- https://github.com/asciidwango/js-primer/issues/1779
> chore: typo

- CLA.md
- textlint/textlint-rule-no-use-column/index.js
- tools/update-package-lock.mjs
CLAとテキストルールの誤字脱字と`tools/update-package-lock.mjs`のリファクタリングを行ったのでご確認お願いいたします。
(js-primer を最近見ており、見るついでに何かしら貢献できればと思っています。
見ていく中で気づいた箇所についてPRを出していこうと思っているのでよろしくお願いいたします。)
> fix & refactor: CLAとテキストルールのエラーメッセージ修正 /  package-lock.jsonの更新処理リファクタリング

- source/cheatsheet/README.md
> chore: ES2025インポート属性の例をチートシートに追加

- source/README.md
- source/intro/README.md
- source/intro/authors/README.md
- source/landing/css/style.css
- source/landing/index.html
> refactor: intro と landing のページの修正

- source/basic/map-and-set/README.md
close https://github.com/asciidwango/js-primer/issues/1806
> feat: Map/SetにSpread構文による展開方法を追加

- source/basic/string/README.md
- source/use-case/nodecli/test/test.js
タイポ修正
- `resouces` → `resources`
-  `flattend` → `flattened `
> chore: タイポ修正

- package-lock.json
- package.json
使用していないと思われるパッケージを削除しました
- `unist-util-find-all-between`
- `unist-util-find-before`
- `unist-util-parents`
> chore: 使用していないパッケージの削除

- package-lock.json
- package.json
- [textlint v15.0.0 | textlint](https://textlint.org/blog/2025/06/22/textlint-15/)
- [Release v15.0.0 · textlint/textlint](https://github.com/textlint/textlint/releases/tag/v15.0.0)
> chore(deps): update to textlint v15
