asciidwango/js-primer

CONTRIBUTING.md, book.json, package.json
https://github.com/azu/gitbook-plugin-canonical-link を使って `<link rel="canonical" >`を付けるようにしました。
目的としてはGitBook.comのプレビュー用のビルドを見えるようにするためです。
以下にプレビュー用に自動ビルドされているGitBookが公開されています。
Pull Requestごとにプレビューを見ることができます。
- https://www.gitbook.com/book/azu/js-primer/details
ビルドしたHTMLには  `<link rel="canonical" >` でGitHub Pages版を参照するようにしているので、Google検索的にも大丈夫になっていると思います。
=> feat(gitbook): canonical linkの設定とGitBook.comビルドについてを追記

book.json, package.json
"japanese-support"が改行を削っていた
close https://github.com/asciidwango/js-primer/issues/105
=> fix(gitbook): 複数行のコードブロックが改行しなくなる問題を修正

source/basic/loop/README.md
多分、 http://teppeis.hatenablog.com/entry/2014/01/surrogate-pair-in-javascript この辺の話が書きたかったのだと思う。
しかし、現在の記述は間違っているので削除する。
書き直すと思うので、Issueはそのまま残しておきます。
refs: #106
=> fix(loop): サロゲートペアの記述を削除

.travis.yml, package.json
`travis-after-all`を使って複数ビルドを待つように
close #160
=> chore(travis): Node.js LTSとstableに固定

source/README.md
目次を整理した。
次の項目は目次から削除。
- 字句構造(文と式)
- 正規表現(文字列に統合
- Intl(でてこないけど、文字列で簡単に触れている
- Unicode(文字列
[標準ビルトインオブジェクト - JavaScript | MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects "標準ビルトインオブジェクト - JavaScript | MDN")
いわゆる低レベルのやつは名前すらでてきてない。
そういうのをまとめて最近のJavaScriptは低レベルなものも増えているよという簡単に名前だけだすコラムかなにかあるといいのかも。
- ArrayBuffer(でてくる気配すらない)
- TypedArray(名前だけ
- Wasm
- 名前だけ出すのはありかも?
close #217
=> refactor(summary): 目次を整理

source/basic/array/README.md
#49 メソッドチェーンについての解説。
メソッドチェーンを配列に持ってきた理由はやっぱりここでもっと利用されているからかなと思ったから(逆にクラスの説明で自作のメソッドチェーンの作成方法はあんまり説明する気がないので関数側より、ユースケースとしての紹介に寄せた)
メソッドチェーンそのものについてだけにしようとしたけど、filer/map/reduceみたいな具体的な例があったほうが見た目的にいいかなと思ってやや無理やり入れている。
- 目的: 配列でよく見かけるパターンであるメソッドチェーンがどのような原理で動いてるかを知る。
- 配列でメソッドチェーンを利用するのは処理を一つのまとまりとして定義し、繋げることができるから
- 具体例: メソッドチェーンをしない場合との比較
- メソッドチェーンがどのような仕組みで動いているのかを確認する
- 具体例: map(a => a * 2).filter(a => a > 10)
- 具体例: アイテムの配列から特定の値段以上の名前を取り出す
- 必要性: メソッドチェーンを利用すれば途中の一時的な変数を作る必要がなくなります。
- あまりに長いメソッドチェーンはあまりに長い関数と同じように読みにくくなりますが、適度な単位で処理を続ける場合にはメソッドチェーンを利用することで簡潔に処理を書けるようになります。
- メソッドチェーンは配列だけではなく、自作のクラスや文字列など様々な場面で利用されます。
- 有名なところではjQueryはメソッドチェーンを多用したライブラリです。
- 配列には配列を返すメソッドとしてArray#mapやArray#filterがありこれを利用した配列の加工処理がメソッドチェーンで書かれることが多いです。
=> feat(array): メソッドチェーンについて

source/basic/loop/README.md
代入される変数を適切なものに変更した
配列の値をcurrentValueに代入しなければ、ログを出せないのに、numという定義してない変数に代入しようとしていて、`ReferenceError: num is not defined`が出ていたので修正した
=> Fix variable name

meetings/2018-02-01/README.md
2018年2月1日に開催したミーティングの記録です。
意見や質問などはこのPull Requestに書いてください
close https://github.com/asciidwango/js-primer/issues/343
=> 2018年2月1日のミーティングノート

config/base.eslintrc.js, source/use-case/nodecli/md-to-html/README.md, source/use-case/nodecli/md-to-html/src/main-4.js
=> fix(usecase/nodecli): Rest/Spreadプロパティを使って書き直し

source/use-case/ajaxapp/xhr/README.md
=> fix(usecase/ajaxapp): 壊れていたリンクを修正

prh.yml, source/basic/function-this/README.md
> "呼び出す"
> 約 3,280,000 件 （0.48 秒） 
> 呼びだす
> 約 37,900 件 （0.38 秒） 
fix https://github.com/asciidwango/js-primer/issues/337
=> style(prh): 呼びだす -> 呼び出す

book.json, package.json
GItBookによってpacakge.jsonは無視されて、npmの本家(バグってる)が参照されていた。
=> fix(website): fix docSearch plugin

source/basic/class/README.md
#39 staticの継承がさりげに登場しているので、
ちゃんと書くか or Dateとかstaticが不要な継承のパターンにしてしまうかかな。
イマイチECMAScriptというか基本文法のレベルだとビルトインオブジェクトの継承するユースケースがない…
ブラウザならHTMLElementとかEventTargetとか、Node.jsならStreamとかEventEmitterとかがあるけど。
まだ、`Error`が登場してないので何か辛いな。
=> feat(class): ビルトインオブジェクトの継承について

source/OUTLINE.md, source/README.md
https://github.com/asciidwango/js-primer/projects/1 に合わせて最終的な第一章の内容に合わせた変更をした。
結果的に含まれなくなる予定の章はOUTLINE.mdに移動した。
=> refactor(basic): 第一章のSUMMARYを更新

source/use-case/nodecli/argument-parse/README.md, source/use-case/nodecli/argument-parse/src/commander-flag.js, source/use-case/nodecli/argument-parse/src/commander-param.js, source/use-case/nodecli/md-to-html/README.md, source/use-case/nodecli/md-to-html/src/main-4.js, source/use-case/nodecli/refactor-and-unittest/src/main-last.js, source/use-case/nodecli/refactor-and-unittest/src/main.js, source/use-case/nodecli/refactor-and-unittest/src/md2html.js, source/use-case/nodecli/refactor-and-unittest/src/test/.editorconfig, source/use-case/nodecli/refactor-and-unittest/src/test/fixtures/expected.html
=> fix(usecase/nodecli): gfmオプションをデフォルトでfalseにする

source/_layouts/website/header.html
ヘッダーの背景色を黒系にして、TOPへのリンクを追加した。
検索で直接たどり着いた人が何のサイトかが分かりやすくするため
=> feat(website): add link to top and logo

source/use-case/todoapp/event-model/README.md, source/use-case/todoapp/event-model/event-emitter/src/EventEmitter.example.js
`EventEmitter`のサンプルコードを修正。
`type`がない時代のサンプルコードが残っていた。
fix #560
=> fix(todo): EventEmitterの実行サンプルを修正

package.json, tools/textstat.js
```
$ node tools/textstat.js | pbcopy
```
した結果を
https://textstat-viewer.netlify.com/
に貼り付けると #554 依存関係の可視化できるようにした。
=> feat(tool): add textstat integration

prh.yml
`prototype`オブジェクトはいいけど、prototypeオブジェクトは避けたいので。
用語統一の辞書
=> chore(prh): prototypeオブジェクト -> プロトタイプオブジェクト

source/basic/async/README.md, source/basic/error-try-catch/README.md, test/markdown-doc-test.js
Fixes #584.
普通は実行されないが、提案通り修正を入れてみました。
この方法で対応すると、新規ラインでなければ、認識されないです。
```javascript
if (true) {
console.log('foo');
} else {
// この文は実行されません
}
```
✅ コード変換適用されます。
---
```javascript
if (true) {
console.log('foo');
} else {
// この文は実行されません
console.error('foo');
}
```
✅ コード変換適用されます。
---
```javascript
if (true) {
console.log('foo');
} else {
console.error('foo'); // この文は実行されません
}
```
❌ コード変換適用されません。
=> feat(doctest): standardize skipped code block

meetings/2019-01-24/README.md
2019年1月24日のミーティングノートです
意見や質問などがありましたらこのPull Requestに書いてください
close #623
=> feat(meeting): 2019-01-24のミーティングノート

source/basic/condition/README.md, source/basic/condition/src/if/leap-year-flat-example.js, source/basic/condition/src/if/leap-year-nest-example.js, source/basic/condition/test/if/leap-year-flat-example-test.js, source/basic/condition/test/if/leap-year-nest-example-test.js, source/basic/function-this/README.md
うるう年の例も出力をわかりやすくした。
ネストが浅い例 もうちょっと読みやすさがわかりやすい例のほうがいい気がする。
fix #646
=> refactor(condition): TODOを修正

source/basic/loop/README.md
=> fix(loop): continueのtypoを修正

source/use-case/nodecli/md-to-html/README.md
README には Option に関する記述が無かったのでドキュメントの対応する場所にリンク先を修正しました。
=> MarkdownをHTMLに変換するページのリンク修正

source/basic/array/README.md
typo修正です。
修正したのですが、`変数宣言する...`よりも
`変数宣言をする...`の方がいい気もしてきました。
ご意見いただければ幸いです。
=> chore: fix typo basic/array/README.md

source/basic/loop/README.md, source/basic/loop/src/while/while-add-example.js, source/basic/loop/test/while/while-add-example-test.js
REPLの仕組み上、最後に評価した値が表示され(xが`10`)とでてしまうのが誤解を生むため修正。
ループ前後で`x`の値を明確に出すようにした
fix #763
=> fix(loop): while文のループログを追加

source/use-case/todoapp/entrypoint/README.md
いつもお世話になっております。
[todoapp](https://jsprimer.net/use-case/todoapp/entrypoint/)のプロジェクトディレクトリ構成について、`index.js`は`todoapp`ディレクトリ直下に存在するため`src/index.js`というタイトルは間違いだと思われます。
=> fix: use-case/todoapp/entrypoint の誤字修正

source/use-case/todoapp/event-model/README.md, source/use-case/todoapp/event-model/event-emitter/src/EventEmitter.example.js, source/use-case/todoapp/event-model/event-emitter/src/EventEmitter.js, source/use-case/todoapp/event-model/event-emitter/src/model/TodoListModel.js, source/use-case/todoapp/final/create-view/src/EventEmitter.js, source/use-case/todoapp/final/create-view/src/model/TodoListModel.js, source/use-case/todoapp/final/final/src/EventEmitter.js, source/use-case/todoapp/final/final/src/model/TodoListModel.js, source/use-case/todoapp/final/final/test/EventEmitter-test.js, source/use-case/todoapp/final/more/src/App.js, source/use-case/todoapp/final/more/src/EventEmitter.js, source/use-case/todoapp/final/more/src/model/TodoListModel.js, source/use-case/todoapp/final/more/test/EventEmitter-test.js, source/use-case/todoapp/update-delete/add-checkbox/src/EventEmitter.js, source/use-case/todoapp/update-delete/add-checkbox/src/model/TodoListModel.js, source/use-case/todoapp/update-delete/delete-feature/src/EventEmitter.js, source/use-case/todoapp/update-delete/delete-feature/src/model/TodoListModel.js, source/use-case/todoapp/update-delete/update-feature/src/EventEmitter.js, source/use-case/todoapp/update-delete/update-feature/src/model/TodoListModel.js
Todoアプリの `EventEmitter` クラス内のメソッド `addEventLister()` および `removeEventLister()` を改名しました。
命名の衝突防止等の理由がございましたら、無視していただいて構いません。
- TodoアプリのドキュメントおよびJSでのメソッド名変更( `src/EventEmitter.js` 内)
- メソッド `EventEmitter#addEventLister()` -> `addEventListener()`
- メソッド `EventEmitter#removeEventLister()` -> `removeEventListener()`
=> fix(todoapp): Rename EventLister -> EventListener (in EventEmitter)

source/use-case/todoapp/event-model/event-emitter/src/model/TodoItemModel.example.js, source/use-case/todoapp/event-model/event-emitter/src/model/TodoListModel.example.js
TodoItemModelとTodoListModelの例として載っているTodoItemModel.example.jsとTodoListModel.example.jsのimportのパスに.jsがついていなかったので追加しました．
=> TodoItemModelとTodoListModelの例でimportしているパスを修正

source/use-case/todoapp/event-model/README.md, source/use-case/todoapp/event-model/event-emitter/src/App.js, source/use-case/todoapp/event-model/event-emitter/src/model/TodoListModel.example.js, source/use-case/todoapp/event-model/event-emitter/src/model/TodoListModel.js, source/use-case/todoapp/final/create-view/src/App.js, source/use-case/todoapp/final/create-view/src/model/TodoListModel.example.js, source/use-case/todoapp/final/create-view/src/model/TodoListModel.js, source/use-case/todoapp/final/final/src/App.js, source/use-case/todoapp/final/final/src/model/TodoListModel.example.js, source/use-case/todoapp/final/final/src/model/TodoListModel.js, source/use-case/todoapp/final/more/src/App.js, source/use-case/todoapp/final/more/src/model/TodoListModel.js, source/use-case/todoapp/update-delete/add-checkbox/src/App.js, source/use-case/todoapp/update-delete/add-checkbox/src/model/TodoListModel.example.js, source/use-case/todoapp/update-delete/add-checkbox/src/model/TodoListModel.js, source/use-case/todoapp/update-delete/delete-feature/src/App.js, source/use-case/todoapp/update-delete/delete-feature/src/model/TodoListModel.example.js, source/use-case/todoapp/update-delete/delete-feature/src/model/TodoListModel.js, source/use-case/todoapp/update-delete/update-feature/src/App.js, source/use-case/todoapp/update-delete/update-feature/src/model/TodoListModel.example.js, source/use-case/todoapp/update-delete/update-feature/src/model/TodoListModel.js
TodoListModelで`get totalCount`と`getTodoItems()`という命名規則の混在があった
(getなのに定義方法がバラバラ)
これを`getXXX`メソッドに統一し、getterを使わなくする。
特にgetterである必要性はないのと、だれが見ても何を求めているのかがわかりやすいことを優先している
(getXXXみたいな命名はダサい所はあるけど、無理してgetterに統一する意味もないのと、getterよりはメソッドの方が見た目でわかりやすい気がする。結局、この辺は好みの問題になりそう。)
fix https://github.com/asciidwango/js-primer/pull/782
📝 その他の修正案
- https://github.com/asciidwango/js-primer/pull/782#discussion_r283121323 を参照
/cc @otokunaga2
=> refactor(todo): `TodoListModel#totalCount` を `TodoListModel#getTotalCount`メソッドに変更

source/use-case/ajaxapp/promise/README.md
Ajaxで通信 -> Promiseを活用する -> 関数の分割
の節でindex.jsでmain関数を作ったあとはindex.htmlのclickイベントをgetUserInfo関数からmain関数にしなければならないが，その説明が載っていなかったので追加しました．
=> fix(ajax):Ajaxの章でindex.htmlの説明を追加した

meetings/2019-05-30/README.md
今回はほとんどがレビューフィードバックの読み合わせだったのでログらしいログはありません。
フィードバックを元に作成したIssue一覧を書いています。
* [all: typeof 演算子の結果とか被る変数名は避ける · Issue #804 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/804)
* [モジュールの章を移動する · Issue #644 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/644)
* [アプリケーション開発の準備 に ローカルサーバの立ち上げ方法を追加する · Issue #805 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/805)
* [変数と宣言: const, let, varの順番で解説を書きなおす · Issue #806 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/806)
* [strict modeについて補足/リンクを入れる · Issue #807 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/807)
* [プロトタイプオブジェクト: 章の最初に目的を入れる · Issue #809 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/ …
=> feat(meeting): 2019-05-30のミーティングログ

source/basic/data-type/src/octal-legacy-literal-invalid.js
consoleのコードと結果が一致していないようだったので修正しました。
(直前の例で、`0o777` を使っていたので、そちらに合わせる形でコードの方を直しました。)
=> chore: consoleのコードと結果を一致させる

README.md, book.json, source/index.md, source/landing/index.html
#860 タイトルは"JavaScript Primer"に決定した。略称は js-primer を維持。
サブタイトルはまだ検討中。
- タイトルを"JavaScript Primer"に変更
- WIPを外した
=> chore: タイトルをJavaScript Primerに決定

source/basic/string/README.md
matches.lastIndexを実行するとundefinedになるので、lastIndexのレシーバーをalphabetsPatternに修正いたしました。
ご確認をお願いします！
=> fix: matches.lastIndex

source/use-case/todoapp/final/more/src/model/TodoListModel.js
以下のメソッドで `TodoListModel#offChange` が呼ばれているのですが、未定義のようだったので追加しました。
https://github.com/asciidwango/js-primer/blob/f0bb4c986c788473790f52fd6e1b704d9434259c/source/use-case/todoapp/final/more/src/App.js#L85-L91
=> fix: 未定義エラーになっていた関数を定義する (EventListenerの解除)

README.md, book.json, source/use-case/nodecli/argument-parse/README.md, source/use-case/nodecli/helloworld/README.md
#976 の対応です。
ref
https://nodejs.org/en/blog/release/v12.13.0/
=> fix: Node.js と npm のバージョンを LTS に合わせる

source/use-case/ajaxapp/display/src/index.js, source/use-case/ajaxapp/http/README.md, source/use-case/ajaxapp/http/src/index.js, source/use-case/ajaxapp/promise/README.md, source/use-case/ajaxapp/promise/src/index.js, source/use-case/ajaxapp/src/index.js
`userId` に `../` とか入れると意図しない感じになるので、単純に `encodeURIComponent` を使うようにした
=> fix(ajax): userIdをencodeURIComponentでエスケープするように

source/landing/index.html
=> chore(title): "JavaScript Primer - 迷わないための入門書"に変更

TeX/chap05.tex
=> fix(chap05): "コラム" を避ける

TeX/chap30.tex, TeX/chap31.tex
chap32だと「アプリケーション開発の準備」の章になっているので他の章もあわせる。
=> fix(chap30/chap31): "「アプリケーション開発の準備」の章"に統一

source/basic/statement-expression/README.md
第一部 基本文法の「文と式」にtypoがあったので修正しました。
ご確認よろしくお願いいたします。
=> chore: fix typo in statement-expression

source/basic/string/README.md
「文字列」の章の「文字列の組み立て」節における `stripSlashBaseURl` という変数名ですが、末尾の `l` が小文字になっており、タイポと思われるので修正します。
=> chore(string): stripSlashBaseURl -> stripSlashBaseURL

source/use-case/nodecli/md-to-html/README.md, source/use-case/nodecli/md-to-html/src/package-lock.json, source/use-case/nodecli/md-to-html/src/package.json, source/use-case/nodecli/refactor-and-unittest/src/package-lock.json, source/use-case/nodecli/refactor-and-unittest/src/package.json
#1155 の対応です。
下記ページの内容を`1.0.0`で動かしてみましたが、問題ありませんでした。
https://jsprimer.net/use-case/nodecli/md-to-html/
=> fix(use-case/nodecli): update marked@1.0.0

source/basic/loop/README.md
`for...in`文がプロパティを列挙する順番はES2019までは実装依存だった。
これがES2020では仕様として列挙する順番が規程されたので、異なる列挙をするブラウザは基本的になくなる。(現時点ではすでにどのブラウザも同じ順番)
背景としては、`Reflect.ownKeys`(ES2015)が入った際に大体の実装が同じ列挙順に統一されたため、仕様が修正された。
詳細
- https://github.com/tc39/proposal-for-in-order
- https://github.com/tc39/proposal-for-in-order/blob/master/exploration/README.md
- https://github.com/tc39/ecma262/pull/1791 仕様の修正
- https://github.com/tc39/test262/pull/2432 テストの実装
fix #1180
=> fix(loop): for...in文についてのES2020の変更点を反映

source/README.md, source/cheetsheet/README.md, source/use-case/README.md
「Ajax通信」の表記をページ側のタイトルに合わせて統一しました。
https://www.kadokawa.co.jp/product/302003000984/
書籍版の目次は「第30章 ユースケース: Ajax通信」になってますね。
=> chore: サマリの表記を修正

source/use-case/ajaxapp/promise/src/index.js, source/use-case/ajaxapp/src/index.js
Fix #1207
本文中では触れていなかったのでサンプルコードのみ。
=> fix(usecase/ajaxapp): userIdを二重にencodeしない

book.json, package-lock.json, package.json
JavaScript Primer のウェブサイト版（https://jsprimer.net/） 画面右下の
「Bug Report」の文言を「問題を報告する」に変更しました。
このissue（https://github.com/asciidwango/js-primer/issues/1209） の対応です。
ご確認よろしくお願いします。
=> feat(website): change bug report word

source/_layouts/website/page.html
画面右下の不具合報告ボタンにスタイルを当てました。
このissue（https://github.com/asciidwango/js-primer/issues/1209） の対応です。
・色はヘッダーの色に合わせています。（`#333`）
・画面右上のページ内リンクのアイコンに合わせて少し透過させています。（ホバー時に透過しなくなります）
・画面右上のページ内リンクのアイコンに合わせて右余白を入れています。
気になる点、あればお申し付けください。
ご確認お願いします。
=> feat(website): add style to bug report

source/basic/read-eval-print/README.md
次の Issue の修正案です。
fix https://github.com/asciidwango/js-primer/issues/1217
`unexpected token: identifier` を直接に表現する意図です。
=> SyntaxError: unexpected token: identifier の説明修正

source/basic/data-type/README.md
RegExp.prototype.test() は文字列を扱います。
このサンプルだと数値の字面をそのまま扱うように勘違いする可能性がありそうで、文字列に変換されるステップを記載しました。
例えば /64/.test(0x64) のように見た目は 同じ64 でも false になる場合などです。
=> 正規表現リテラルのサンプルコードの修正

package.json, source/use-case/nodecli/refactor-and-unittest/src/test/md2html-test.js
https://github.com/asciidwango/js-primer/issues/1233
=> fix(nodecli): 末尾の改行コードを削除

source/basic/array/README.md
Array#sliceでは第一引数と第二引数が同一の場合も空配列となるので、
その意味も含めて`>`ではなく`>=`もしくは`≧`が良いと思います。
ささいな修正で恐縮ですが、上から読んでいった時に気になったので提案させて頂きました。
（このレベルならIssueの方が良い、等あればお教えください。）
過去の議論としては https://github.com/asciidwango/js-primer/issues/1163 とも関連すると思います。
=> Array#sliceにおいて空配列となる場合の引数の条件を修正

CONTRIBUTING.md, README.md
READMEやCONTRIBUTINGの中にあるGitBookをHonKitに変更しました
fix #1176
=> fix: GitBookをHonKitに変更する

source/_layouts/website/page.html
close #1253
見出しのリンクと被さってしまうことを回避するため、page.htmlに以下を追記しました。
`navigation-prev`だけスタイルをあてるとナビゲーション左右のバランスが崩れて見えるので両方に当てました。
```css
.navigation {
min-width: 50px;
}
```
▼修正前
▼修正後
=> Navigationリンクのmin-widthを調整

source/use-case/todoapp/entrypoint/README.md
本文が ウェブコンソール、リンク定義が Webコンソールとなっていてリンクが生成されないようです。
MDN ページもウェブコンソールを開くとなっているので、本文に合わせてリンク定義を修正するものです。
修正箇所：https://jsprimer.net/use-case/todoapp/entrypoint/#view-console-log-in-dev-tools
=> リンク定義の Typo 修正

source/basic/async/README.md
こんにちは 👋 , js-primerには大変お世話になっています！
関数宣言の末尾にセミコロンが入っていたので削除しました。ご確認頂けると嬉しいです。
=> 不要なセミコロンを削除

source/landing/css/style.css, source/landing/index.html
ランディングページに更新情報を購読できるフォームがあったので、登録させていただきました。
登録した際に、ボタンの文字色と背景色のコントラスト比が少し低いように感じたので修正しました。
現在のコントラスト比は 2.12 ですが、[Web Content Accessibility Guidelines](https://webaim.org/standards/wcag/) では 4.5 以上が推奨されているので、`hover` 時にそれを下回らない背景色に修正しました。
> WebAIM のガイドライン では、すべてのテキストで AA（最小）コントラスト比 4.5:1 を推奨しています。例外は、非常に大きなテキストです（デフォルトの本文テキストより 120～150% 大きい）。この場合、推奨されるコントラスト比は 3:1 です。
> ref: https://developers.google.com/web/fundamentals/accessibility/accessible-styles)
サイトの統一感を崩さないために、背景色は #1213 の「問題を報告する」ボタンに寄せました。
=> fix(website): 登録ボタンのコントラスト比の改善

.github/workflows/deploy.yml, .github/workflows/test.yml, README.md, book.json, source/use-case/nodecli/argument-parse/README.md, source/use-case/nodecli/helloworld/README.md
=> feat(node): Update to Node.js 14.15.0(LTS)

source/use-case/nodecli/md-to-html/README.md
- [use-case/nodecli/argument-parse/README.md の脚注1](https://jsprimer.net/use-case/nodecli/argument-parse/#fn_1) で `--save` オプションを省略しているため統一
- リンクの記述法を修正
- リンクの `[]` 内で `\[` `\]` では角括弧をエスケープできなかったため `&#91;` `&#93` のように記述しましたが, 望ましくない場合修正します (`npm run start` 後に Firefox 84.0.2 で確認)
=> chore(use-case/nodecli): unify style

source/use-case/nodecli/argument-parse/src/package-lock.json, source/use-case/nodecli/md-to-html/README.md, source/use-case/nodecli/md-to-html/src/main-1.js, source/use-case/nodecli/md-to-html/src/main-2.js, source/use-case/nodecli/md-to-html/src/main-3.js, source/use-case/nodecli/md-to-html/src/main.js, source/use-case/nodecli/md-to-html/src/package-lock.json, source/use-case/nodecli/md-to-html/src/package.json, source/use-case/nodecli/refactor-and-unittest/src/main-last.js, source/use-case/nodecli/refactor-and-unittest/src/md2html.js, source/use-case/nodecli/refactor-and-unittest/src/package-lock.json, source/use-case/nodecli/refactor-and-unittest/src/package.json
fix #1377 
md-to-htmlとrefactor-and-unittestで利用しているmarkedのバージョンを最新の4系へ更新しました。
それに伴って関数の呼び出しが `marked(html)` -> `marked.parse(html)` へ変更されたので置換して、testが通ることを確認しました。
=> markedパッケージのバージョンを1.0.0から最新の4.0.10へ更新

source/basic/data-type/README.md, source/basic/function-this/README.md, source/basic/object/README.md, source/basic/string/README.md
Closes #807
- 各 `README.md` における `strict mode` の初出箇所にリンクを追加
対象:
```console
kangetsu@ubuntu20:~/work/js-primer$ grep -rli 'strict mode' ./source/ | grep README.md | grep -v introduction
./source/basic/object/README.md
./source/basic/string/README.md
./source/basic/data-type/README.md
./source/basic/function-this/README.md
kangetsu@ubuntu20:~/work/js-primer$ 
```
=> chore: add links of strict mode

source/basic/implicit-coercion/README.md
Closes #1410
[暗黙的な型変換 | 文字列 → 数値](https://jsprimer.net/basic/implicit-coercion/#string-to-number) で、コードの内容を説明文に沿ったものにする
=> `NaN`になってしまった場合の処理をより明確にする

source/cheatsheet/README.md
こちらのTweetで募集していたプルリクエストを作成しました。
https://twitter.com/azu_re/status/1534017734526111744?s=20&t=tWTGkYwUt1YucRxy-OadvQ
- 「HTML-like コメント」についてはMDNのドキュメントで見つからなかったため空白にしています
- リンクのタイトルはMDNのドキュメントのタイトルにしています
=> feat(cheetsheet): MDNの対応リンクを追加

source/cheatsheet/README.md
=> chore(cheatsheet): MDNの対応リンクが一部間違っていたため修正

source/cheatsheet/README.md
| コード例 | 説明 | 解説 | MDN | 
| -- | -- | -- | -- |
| 45% | 30% | 15% | 10% | 
にしてみた。
- コード例は折り返さないようにする(40%ちょいで足りていそう。画面幅によるけど)
- 説明はある程度読める感じ
- 解説とMDNは1文字折り返しがなくなればいい
fix #1435 
cc @yo-goto
=> fix(cheatsheet): テーブルの幅を固定

source/basic/math/README.md
80行目の文章では「床関数」と記載されているのに、その下のサンプルコードでは、「底関数」と記載されていました。
- #1243 で、「床関数」のほうが正しいと判断し、「床関数」に変更いたしました。
=> サンプルコードの「底関数」を「床関数」に変更しました

source/basic/data-type/README.md, source/basic/data-type/src/var-null-invalid.js
`var` を使う必要がない (巻き上げなどの挙動が不要) 場面での `var` を `const` に置換しました
`var` の利用が意図的であればお手数ですがクローズお願いします。
使える箇所では `const` がより良いと考えているため `const` にしましたが、`let` の方が良いなどあれば修正いたします。
動作、`npm test` は確認済みです。
=> chore(basic/data-type): replace unnecessary var with const

source/appendix/links/README.md, source/basic/read-eval-print/README.md, source/use-case/setup-local-env/README.md
Atomは公式に非推奨となったため。
> On December 15, 2022, we will archive the atom/atom repository and all other repositories remaining in the Atom organization.
> [Sunsetting Atom | The GitHub Blog](https://github.blog/2022-06-08-sunsetting-atom/)
fix #1461
=> fix: Atomの言及を削除

source/basic/async/README.md
以下の非同期処理:Promise/Async Function内に誤字と思われる箇所があったので、
> [ES2022] Module直下でのawait式
> ES2021までは、await式はAsync Functionの直下でのみ利用な可能なことを紹介しました。 ES2022には、これに加えてModuleの直下ではAsync Functionで囲まなくてもawait式が利用できます。
> https://jsprimer.net/basic/async/#top-level-await-in-module
「利用な可能なこと -> 利用可能なこと」に修正しました。
=> 非同期処理:Promise/Async Function内の誤字と思われる箇所を修正

README.md, book.json, meetings/2017-02-24/README.md, package.json, source/basic/ecmascript/README.md, source/use-case/nodecli/argument-parse/README.md, source/use-case/nodecli/helloworld/README.md
[Node v18.12.0 (LTS) | Node.js](https://nodejs.org/en/blog/release/v18.12.0/) へアップデート
fix #1437
=> fix: Node.js v18.12.0 LTSにアップデート

source/basic/class/README.md
- クラスフィールドが宣言的であるメリット
- private class fieldの例を追加
=> fix: private class fieldsの補完

package-lock.json, package.json, source/_layouts/website/page.html, source/use-case/ajaxapp/display/README.md, source/use-case/ajaxapp/entrypoint/README.md, source/use-case/ajaxapp/http/README.md, source/use-case/ajaxapp/promise/README.md
=> add sandpack to ajaxapp

source/use-case/ajaxapp/display/README.md, source/use-case/ajaxapp/entrypoint/README.md, source/use-case/ajaxapp/http/README.md, source/use-case/ajaxapp/promise/README.md
`globalThis.fetchUserInfo = fetchUserInfo;` を末尾に動的に作って追加することで、onclick="fetchUserInfo()" が動くようにした
fix https://github.com/asciidwango/js-primer/pull/1423
fix https://github.com/asciidwango/js-primer/issues/1520
=> fix(ajax): externalResourcesではなく、動的に末尾にglobalThisでグローバルに関数を追加した

source/use-case/todoapp/event-model/event-emitter/src/App.js, source/use-case/todoapp/final/create-view/src/view/TodoListView.js, source/use-case/todoapp/final/final/src/view/TodoListView.js, source/use-case/todoapp/final/more/src/view/TodoListView.js, source/use-case/todoapp/form-event/add-todo-item/src/App.js, source/use-case/todoapp/update-delete/add-checkbox/src/App.js, source/use-case/todoapp/update-delete/delete-feature/src/App.js, source/use-case/todoapp/update-delete/update-feature/src/App.js
`<ul />` は結果として動いてるけど、空の`<ul></ul>` を作るという意味では微妙にうまくいかないケースがあるため、 `<ul></ul>` に変更。
背景:
- `<ul />` → `<ul></ul>` に変更
- `<ul />` 自体の解説がない
- `<ul/> test` のように書くと意味が異なる
fix #1508
=> fix(todoapp): <ul /> を <ul></ul> に変更

source/use-case/nodecli/md-to-html/README.md
以下ページの誤記修正です。
MarkdownをHTMLに変換する
https://jsprimer.net/use-case/nodecli/md-to-html
同じ内容の文章が２回書かれていましたので、一方を削除しました。
=> fix: Removed redundant text

source/basic/variables/README.md
「初期値を」では文法的に少しおかしいため、「初期値が」へと修正しました。
=> fix: typo を修正

source/basic/operator/README.md
9 の二進数表現 (0b1001) とすべき（と思われる）コードが 15 (0b1111) になっていたため、修正しました。
=> fix: 9 の二進数表現の誤りを修正

source/basic/array/README.md
「配列」の章において何点か誤記や記述が一貫性を欠く箇所などを見つけたため、修正しました。
=> fix: 「配列」の章における typo などを修正

source/basic/condition/README.md
https://jsprimer.net/basic/condition/#else-if-statement において、backtick (\`) による囲み忘れと思われる箇所があったため、修正しました。
=> fix: 「条件分岐」の章において、コードとして表記すべき箇所を backtick で囲む

source/basic/condition/README.md
「関数と宣言」は「条件分岐」の章よりも前であるため、表現を改めました。
=> fix: 「条件分岐」の章において、それよりも前の章が後の章であるかのように表現されているため、修正

source/basic/statement-expression/README.md
https://github.com/asciidwango/js-primer/discussions/1547#discussioncomment-4905241 にて「function宣言（文）とfunction式」というセクションタイトルを「関数宣言（文）と関数式」へと変更して問題ないとなったため、それを適用しました。
=> fix: 「文と式」におけるセクションのタイトルを漢字に変更

source/basic/object/README.md
[オブジェクト#[コラム] constで定義したオブジェクトは変更可能](https://jsprimer.net/basic/object/#const-and-object)
ブラウザ環境やランタイム環境(Node)で確認したところ、再代入によって発生する例外はTypeErrorだったため修正しました。
参考:
=> constで定義したオブジェクトへの再代入で発生する例外を修正した

meetings/2023-01-12/README.md, meetings/2023-02-16/README.md
2023-01-12(追加し忘れ)と2023-02-16のミーティングノートです。
- [2023-02-16のミーティングアジェンダ · Discussion #1589 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/discussions/1589)
- [2023-01-12のミーティングアジェンダ · Discussion #1544 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/discussions/1544) 
意見や質問はこのPRやDiscussionに書いてください。
=> 2023-01-12と2023-02-16のミーティングノート

source/basic/wrapper-object/README.md
タイトル通り、「ラッパーオブジェクト」の章でオブジェクトをもつプリミティブ型の記述に BigInt が抜けていたため追加しました。
=> fix: 「ラッパーオブジェクト」におけるオブジェクトをもつプリミティブ型の記述に BigInt を追加

source/basic/class/README.md
クラスの[Privateクラスフィールド](https://jsprimer.net/basic/class/#private-class-fields)の項にて、一箇所「アクセサプロパティ」という記述があったため、その箇所以外で使われている「アクセッサプロパティ」へと統一するよう修正しました。ご検討ください。
=> アクセサプロパティをアクセッサプロパティへと統一するように修正した

source/basic/statement-expression/src/statement-not-expression-invalid.js
「文と式」の[文](https://jsprimer.net/basic/statement-expression/#statement)の項において varを使っている理由は特段ないとのことだったので、推奨されているconstに変更しました。
この変更で本来伝えたいことには影響することはありません。
- refs : https://github.com/asciidwango/js-primer/discussions/1547#discussioncomment-5021002
=> SyntaxErrorが出るサンプルコードで変数宣言の部分をvarからconstに変更した

source/basic/module/src/named-import.js
https://jsprimer.net/basic/module/#named-export-import において、my-module.js の内容が
```js
export const foo = "foo";
export function bar() { }
```
となっているにも関わらず、そこから名前付きインポートした bar を console.log した出力が `"bar"` となっていたため、Firefox で bar 関数を console.log した際の出力内容に修正しました。
=> fix: 「ECMAScriptモジュール」において console.log の内容が誤っている箇所を修正

source/use-case/ajaxapp/entrypoint/README.md
かなり細かい話ですが、「エントリーポイント」https://jsprimer.net/use-case/ajaxapp/entrypoint/ において不要なスペースがコメントに含まれている箇所を見つけたため、一応削除しておきました。
=> fix: 「エントリーポイント」におけるコメント内の不要スペースを削除

prh.yml
- Issue #1611 
- refs: #1608, #1610
アクセッサプロパティとBigIntを表記揺れの辞書に追加しました。
追加する場所等わからなかったので任意の場所に差し込んでいます。不適切な場合、ご指摘ください:bow:
=> アクセッサプロパティとBigIntを表記揺れの辞書に追加した

source/basic/operator/README.md
#1616 の対応
0除算の結果がエラーにならず、Inifinityになることを追記する
https://jsprimer.net/basic/operator/#division-operator
負の無限大になるケースも併せて記載しています。
=> fix: 0除算の結果がエラーにならず、Infinityになることの説明追記(#1616)

package-lock.json, package.json, test/lib/testing-code.js
`vm2` is discontinue.
- https://github.com/advisories/GHSA-cchq-frgv-rjh5
- https://github.com/patriksimek/vm2/issues/533
Update power-doctest and Use `vm` instead of `vm2`.
- https://github.com/azu/power-doctest/releases/tag/v5.3.3
📝 Sandbox feature is unnessary on our usecase.
=> fix: update power-doctest and remove vm2

CLA.md, LICENSE-CC-BY, LICENSE-MIT, README.md, source/intro/README.md
文章のライセンスを[CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/deed.ja)から[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.ja)へ変更する。
CC BY-NCでは商用利用を禁止する条項があるが、
CC BYにはこの条項は含まれなくなる。
| 行為            | CC BY | CC BY-NC |
| -------------- | ----- | -------- |
| 複製           | OK    | OK       |
| 頒布           | OK    | OK       |
| 展示           | OK    | OK       |
| 実演           | OK    | OK       |
| 改変           | OK    | OK       |
| 著作権者の表示 | 必要  | 必要     |
| **非営利目的**     | OK    | NG       |
- fix #1690
=> fix(license): CC BY-NC → CC BYにライセンスを変更

README.md, source/intro/README.md
- ref #1674 
- close #1658 
それぞれのリンクを追加
- [JavaScript Primer - Open Collective](https://opencollective.com/jsprimer)
- [Release v5.0.0: ES2023/CC BYライセンスに変更/Open Collective · asciidwango/js-primer](https://github.com/asciidwango/js-primer/releases/tag/v5.0.0)
=> feat: 支援方法にOpen Collectiveを追加/リリースノートへのリンクを追加

source/use-case/nodecli/argument-parse/README.md, source/use-case/setup-local-env/README.md
- Node.js の日本語版ページ https://nodejs.org/ja/が404を返すため、英語版ページ https://nodejs.org/ へのリンクに変更しました
=> fix: Node.js の日本語版ページがリンク切れのためリンク先を英語版ページに変更

source/basic/ecmascript/README.md
URL: https://jsprimer.net/basic/ecmascript/
> Polyfillを提供するものとしてはcore-jsやpolyfill.ioなどが有名です。
リンクが切れているのとドメインが信頼できないため削除して、修正または注意の追記を行う必要がありそうです
https://blog.cloudflare.com/polyfill-io-now-available-on-cdnjs-reduce-your-supply-chain-risk
https://cdnjs.cloudflare.com/polyfill/ や https://polyfill-fastly.io/ にリンクを変更してもいいかもとも思いましたが、polyfillとは何かの説明がこの文の主題で、例として挙げているだけだと思うので記述自体必要ないと思いましたが、どうでしょうか？
=> fix(basic/ecmascript/): polyfilioの記述とリンクを削除する

source/basic/operator/README.md
「文字列結合演算子」は「二項演算子」のセクション内だと考えられ、また前後の階層レベルが `###` なのでそれと合わせました。
before:
after:
=> fix(operator): 「文字列結合演算子」の階層レベルを前後と揃える

package-lock.json, package.json
https://github.com/textlint-rule/textlint-rule-eslint/releases/tag/v5.0.1
```diff
> js-primer@6.0.0 textlint
> summary-to-path ./source/README.md | xargs textlint -f pretty-error --cache
- corepack npm run textlint  18.11s user 2.09s system 115% cpu 17.484 total
+ corepack npm run textlint  15.32s user 1.25s system 116% cpu 14.280 total
```
=> chore(deps): update eslint

source/basic/map-and-set/README.md
ショッピングカートの例が複雑なので、シンプルにキーにオブジェクトを使えるという例に変更した
- ショッピングカートの例を削除し、オブジェクトをキーにする利点を強調
- 新しい例として、異なるオブジェクトをキーにしたMapの使用法を追加
fix #1750
=> refactor(map-and-set): Mapのキーとしてオブジェクトを使う例をシンプルなものに変更

CONTRIBUTING_EXPENSE.md
Open Collectiveで支払いを受け取る代わりに、別のCollectiveに対して同額を寄付するオプションを追加
=> docs: 支払い方法の選択に関するセクションを追加

.mcp.json, .textlintrc.js, .vscode/mcp.json
iterator-helpersブランチから必要な設定ファイルを移植しました。
- `.mcp.json`と`.vscode/mcp.json`にtextlint MCPサーバー設定を追加
- VSCodeでMCP（Model Context Protocol）を使用してtextlintを実行できるようになります
- `TEXTLINT_MCP=true`環境変数が設定されます
- `.textlintrc.js`にAI向けルール（`@textlint-ja/preset-ai-writing`）を追加
- `TEXTLINT_MCP=true`環境変数が設定されている場合のみ有効になります
- iterator-helpersブランチで開発されていた設定を移植
=> feat: textlintのMCP設定
